// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RAD_Lab5.Data;

#nullable disable

namespace RAD_Lab5.Migrations.Rad_Lab5Fluent
{
    [DbContext(typeof(Rad_Lab5FluentContext))]
    [Migration("20241025232647_updated")]
    partial class updated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RAD_Lab5.Models.FluentUser", b =>
                {
                    b.Property<int>("UniqueIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UniqueIdentifier"));

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("user_age");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Title")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "Title");

                    b.HasKey("UniqueIdentifier");

                    b.ToTable("FluentUser", (string)null);

                    b.SplitToTable("Biography", null, t =>
                        {
                            t.Property("UniqueIdentifier");

                            t.Property("Biography");

                            t.Property("Title");
                        });
                });

            modelBuilder.Entity("RAD_Lab5.Models.FluentUser", b =>
                {
                    b.HasOne("RAD_Lab5.Models.FluentUser", null)
                        .WithOne()
                        .HasForeignKey("RAD_Lab5.Models.FluentUser", "UniqueIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
